//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Ingame"",
            ""id"": ""20019ef3-16ee-4321-8e6c-3cf06717356f"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4daef9f5-e270-43f1-bb65-081658f7fdd1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BaseMinionControlGroup"",
                    ""type"": ""Button"",
                    ""id"": ""18731677-1764-4609-ac80-935453c56225"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RangedMinionControlGroup"",
                    ""type"": ""Button"",
                    ""id"": ""388c76af-acc5-4891-af84-734710a80112"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TankMinionControlGroup"",
                    ""type"": ""Button"",
                    ""id"": ""ccf6c5ac-b978-493e-9eca-92fb3c957f8f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MagicMinionControlGroup"",
                    ""type"": ""Button"",
                    ""id"": ""8633a75e-f9d2-45a3-b540-d5e69e3ba241"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UpMenuButton"",
                    ""type"": ""Button"",
                    ""id"": ""78847ce8-3bb2-4ee8-880c-3b3e191feadf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftMenuButton"",
                    ""type"": ""Button"",
                    ""id"": ""3351623a-b070-424a-8479-7311126d9c40"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightMenuButton"",
                    ""type"": ""Button"",
                    ""id"": ""86df74de-1863-48ae-ab2e-15e0615c7acc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DownMenuButton"",
                    ""type"": ""Button"",
                    ""id"": ""841843ed-b05e-4af2-a9fc-83b092a9871a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleAutoActive"",
                    ""type"": ""Button"",
                    ""id"": ""ab5e51b2-fc12-4886-b354-79fce0b333bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ConfirmMenuButton"",
                    ""type"": ""Button"",
                    ""id"": ""d8e9d990-27b3-483a-ba81-696fdcbf9c26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BackMenuButton"",
                    ""type"": ""Button"",
                    ""id"": ""32906df8-2eab-4884-8177-2d81553db12c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WakeMinions"",
                    ""type"": ""Button"",
                    ""id"": ""7a2074cc-992e-4cdf-ac5c-8c1f0a342131"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""cbba0cd3-e3b3-4a84-bf60-7e24a2ca3904"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a47ab1d1-f01a-4bf5-8a75-4e5984a71caa"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad Scheme"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bba1a590-42d3-41da-b7c5-446565850fa1"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad Scheme"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""11b1520f-cd3e-46f0-a711-32a158724b61"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad Scheme"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""68d9aeee-c724-44d1-ba38-5cfb8b605d3e"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad Scheme"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e660a879-a37e-4608-8157-fee73b442a67"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad Scheme"",
                    ""action"": ""BaseMinionControlGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a54a584e-2303-4293-b588-3a6c8f3046fb"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad Scheme"",
                    ""action"": ""RangedMinionControlGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a063bbf-c7a3-46e2-8650-f11aad968f54"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad Scheme"",
                    ""action"": ""TankMinionControlGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b5d2299-a68f-4f2c-86a6-ea5146f1c4fa"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad Scheme"",
                    ""action"": ""MagicMinionControlGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0c58754-b1e4-4ab4-bff1-314c8bcb43b7"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad Scheme"",
                    ""action"": ""UpMenuButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61de9e99-acc5-45ba-bb0c-64b0aff2810b"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad Scheme"",
                    ""action"": ""LeftMenuButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7cc1c48a-501d-4ae5-bf24-3284166d96bb"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad Scheme"",
                    ""action"": ""RightMenuButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bafcf924-6881-4ed0-9220-b9f85ca00c65"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad Scheme"",
                    ""action"": ""DownMenuButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""872d13a0-cc39-4326-8e93-0f06a3e19c99"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad Scheme"",
                    ""action"": ""ToggleAutoActive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8b93313-cb6b-4eba-9552-947d15ad6c58"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad Scheme"",
                    ""action"": ""ConfirmMenuButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e1624c7-4af4-4f80-80eb-dee7e7b1fabf"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad Scheme"",
                    ""action"": ""BackMenuButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bcba22d0-c73e-4499-8a6f-6f171cc0e5e2"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad Scheme"",
                    ""action"": ""WakeMinions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Gamepad Scheme"",
            ""bindingGroup"": ""Gamepad Scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Ingame
        m_Ingame = asset.FindActionMap("Ingame", throwIfNotFound: true);
        m_Ingame_Movement = m_Ingame.FindAction("Movement", throwIfNotFound: true);
        m_Ingame_BaseMinionControlGroup = m_Ingame.FindAction("BaseMinionControlGroup", throwIfNotFound: true);
        m_Ingame_RangedMinionControlGroup = m_Ingame.FindAction("RangedMinionControlGroup", throwIfNotFound: true);
        m_Ingame_TankMinionControlGroup = m_Ingame.FindAction("TankMinionControlGroup", throwIfNotFound: true);
        m_Ingame_MagicMinionControlGroup = m_Ingame.FindAction("MagicMinionControlGroup", throwIfNotFound: true);
        m_Ingame_UpMenuButton = m_Ingame.FindAction("UpMenuButton", throwIfNotFound: true);
        m_Ingame_LeftMenuButton = m_Ingame.FindAction("LeftMenuButton", throwIfNotFound: true);
        m_Ingame_RightMenuButton = m_Ingame.FindAction("RightMenuButton", throwIfNotFound: true);
        m_Ingame_DownMenuButton = m_Ingame.FindAction("DownMenuButton", throwIfNotFound: true);
        m_Ingame_ToggleAutoActive = m_Ingame.FindAction("ToggleAutoActive", throwIfNotFound: true);
        m_Ingame_ConfirmMenuButton = m_Ingame.FindAction("ConfirmMenuButton", throwIfNotFound: true);
        m_Ingame_BackMenuButton = m_Ingame.FindAction("BackMenuButton", throwIfNotFound: true);
        m_Ingame_WakeMinions = m_Ingame.FindAction("WakeMinions", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Ingame
    private readonly InputActionMap m_Ingame;
    private IIngameActions m_IngameActionsCallbackInterface;
    private readonly InputAction m_Ingame_Movement;
    private readonly InputAction m_Ingame_BaseMinionControlGroup;
    private readonly InputAction m_Ingame_RangedMinionControlGroup;
    private readonly InputAction m_Ingame_TankMinionControlGroup;
    private readonly InputAction m_Ingame_MagicMinionControlGroup;
    private readonly InputAction m_Ingame_UpMenuButton;
    private readonly InputAction m_Ingame_LeftMenuButton;
    private readonly InputAction m_Ingame_RightMenuButton;
    private readonly InputAction m_Ingame_DownMenuButton;
    private readonly InputAction m_Ingame_ToggleAutoActive;
    private readonly InputAction m_Ingame_ConfirmMenuButton;
    private readonly InputAction m_Ingame_BackMenuButton;
    private readonly InputAction m_Ingame_WakeMinions;
    public struct IngameActions
    {
        private @Controls m_Wrapper;
        public IngameActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Ingame_Movement;
        public InputAction @BaseMinionControlGroup => m_Wrapper.m_Ingame_BaseMinionControlGroup;
        public InputAction @RangedMinionControlGroup => m_Wrapper.m_Ingame_RangedMinionControlGroup;
        public InputAction @TankMinionControlGroup => m_Wrapper.m_Ingame_TankMinionControlGroup;
        public InputAction @MagicMinionControlGroup => m_Wrapper.m_Ingame_MagicMinionControlGroup;
        public InputAction @UpMenuButton => m_Wrapper.m_Ingame_UpMenuButton;
        public InputAction @LeftMenuButton => m_Wrapper.m_Ingame_LeftMenuButton;
        public InputAction @RightMenuButton => m_Wrapper.m_Ingame_RightMenuButton;
        public InputAction @DownMenuButton => m_Wrapper.m_Ingame_DownMenuButton;
        public InputAction @ToggleAutoActive => m_Wrapper.m_Ingame_ToggleAutoActive;
        public InputAction @ConfirmMenuButton => m_Wrapper.m_Ingame_ConfirmMenuButton;
        public InputAction @BackMenuButton => m_Wrapper.m_Ingame_BackMenuButton;
        public InputAction @WakeMinions => m_Wrapper.m_Ingame_WakeMinions;
        public InputActionMap Get() { return m_Wrapper.m_Ingame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(IngameActions set) { return set.Get(); }
        public void SetCallbacks(IIngameActions instance)
        {
            if (m_Wrapper.m_IngameActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_IngameActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_IngameActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_IngameActionsCallbackInterface.OnMovement;
                @BaseMinionControlGroup.started -= m_Wrapper.m_IngameActionsCallbackInterface.OnBaseMinionControlGroup;
                @BaseMinionControlGroup.performed -= m_Wrapper.m_IngameActionsCallbackInterface.OnBaseMinionControlGroup;
                @BaseMinionControlGroup.canceled -= m_Wrapper.m_IngameActionsCallbackInterface.OnBaseMinionControlGroup;
                @RangedMinionControlGroup.started -= m_Wrapper.m_IngameActionsCallbackInterface.OnRangedMinionControlGroup;
                @RangedMinionControlGroup.performed -= m_Wrapper.m_IngameActionsCallbackInterface.OnRangedMinionControlGroup;
                @RangedMinionControlGroup.canceled -= m_Wrapper.m_IngameActionsCallbackInterface.OnRangedMinionControlGroup;
                @TankMinionControlGroup.started -= m_Wrapper.m_IngameActionsCallbackInterface.OnTankMinionControlGroup;
                @TankMinionControlGroup.performed -= m_Wrapper.m_IngameActionsCallbackInterface.OnTankMinionControlGroup;
                @TankMinionControlGroup.canceled -= m_Wrapper.m_IngameActionsCallbackInterface.OnTankMinionControlGroup;
                @MagicMinionControlGroup.started -= m_Wrapper.m_IngameActionsCallbackInterface.OnMagicMinionControlGroup;
                @MagicMinionControlGroup.performed -= m_Wrapper.m_IngameActionsCallbackInterface.OnMagicMinionControlGroup;
                @MagicMinionControlGroup.canceled -= m_Wrapper.m_IngameActionsCallbackInterface.OnMagicMinionControlGroup;
                @UpMenuButton.started -= m_Wrapper.m_IngameActionsCallbackInterface.OnUpMenuButton;
                @UpMenuButton.performed -= m_Wrapper.m_IngameActionsCallbackInterface.OnUpMenuButton;
                @UpMenuButton.canceled -= m_Wrapper.m_IngameActionsCallbackInterface.OnUpMenuButton;
                @LeftMenuButton.started -= m_Wrapper.m_IngameActionsCallbackInterface.OnLeftMenuButton;
                @LeftMenuButton.performed -= m_Wrapper.m_IngameActionsCallbackInterface.OnLeftMenuButton;
                @LeftMenuButton.canceled -= m_Wrapper.m_IngameActionsCallbackInterface.OnLeftMenuButton;
                @RightMenuButton.started -= m_Wrapper.m_IngameActionsCallbackInterface.OnRightMenuButton;
                @RightMenuButton.performed -= m_Wrapper.m_IngameActionsCallbackInterface.OnRightMenuButton;
                @RightMenuButton.canceled -= m_Wrapper.m_IngameActionsCallbackInterface.OnRightMenuButton;
                @DownMenuButton.started -= m_Wrapper.m_IngameActionsCallbackInterface.OnDownMenuButton;
                @DownMenuButton.performed -= m_Wrapper.m_IngameActionsCallbackInterface.OnDownMenuButton;
                @DownMenuButton.canceled -= m_Wrapper.m_IngameActionsCallbackInterface.OnDownMenuButton;
                @ToggleAutoActive.started -= m_Wrapper.m_IngameActionsCallbackInterface.OnToggleAutoActive;
                @ToggleAutoActive.performed -= m_Wrapper.m_IngameActionsCallbackInterface.OnToggleAutoActive;
                @ToggleAutoActive.canceled -= m_Wrapper.m_IngameActionsCallbackInterface.OnToggleAutoActive;
                @ConfirmMenuButton.started -= m_Wrapper.m_IngameActionsCallbackInterface.OnConfirmMenuButton;
                @ConfirmMenuButton.performed -= m_Wrapper.m_IngameActionsCallbackInterface.OnConfirmMenuButton;
                @ConfirmMenuButton.canceled -= m_Wrapper.m_IngameActionsCallbackInterface.OnConfirmMenuButton;
                @BackMenuButton.started -= m_Wrapper.m_IngameActionsCallbackInterface.OnBackMenuButton;
                @BackMenuButton.performed -= m_Wrapper.m_IngameActionsCallbackInterface.OnBackMenuButton;
                @BackMenuButton.canceled -= m_Wrapper.m_IngameActionsCallbackInterface.OnBackMenuButton;
                @WakeMinions.started -= m_Wrapper.m_IngameActionsCallbackInterface.OnWakeMinions;
                @WakeMinions.performed -= m_Wrapper.m_IngameActionsCallbackInterface.OnWakeMinions;
                @WakeMinions.canceled -= m_Wrapper.m_IngameActionsCallbackInterface.OnWakeMinions;
            }
            m_Wrapper.m_IngameActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @BaseMinionControlGroup.started += instance.OnBaseMinionControlGroup;
                @BaseMinionControlGroup.performed += instance.OnBaseMinionControlGroup;
                @BaseMinionControlGroup.canceled += instance.OnBaseMinionControlGroup;
                @RangedMinionControlGroup.started += instance.OnRangedMinionControlGroup;
                @RangedMinionControlGroup.performed += instance.OnRangedMinionControlGroup;
                @RangedMinionControlGroup.canceled += instance.OnRangedMinionControlGroup;
                @TankMinionControlGroup.started += instance.OnTankMinionControlGroup;
                @TankMinionControlGroup.performed += instance.OnTankMinionControlGroup;
                @TankMinionControlGroup.canceled += instance.OnTankMinionControlGroup;
                @MagicMinionControlGroup.started += instance.OnMagicMinionControlGroup;
                @MagicMinionControlGroup.performed += instance.OnMagicMinionControlGroup;
                @MagicMinionControlGroup.canceled += instance.OnMagicMinionControlGroup;
                @UpMenuButton.started += instance.OnUpMenuButton;
                @UpMenuButton.performed += instance.OnUpMenuButton;
                @UpMenuButton.canceled += instance.OnUpMenuButton;
                @LeftMenuButton.started += instance.OnLeftMenuButton;
                @LeftMenuButton.performed += instance.OnLeftMenuButton;
                @LeftMenuButton.canceled += instance.OnLeftMenuButton;
                @RightMenuButton.started += instance.OnRightMenuButton;
                @RightMenuButton.performed += instance.OnRightMenuButton;
                @RightMenuButton.canceled += instance.OnRightMenuButton;
                @DownMenuButton.started += instance.OnDownMenuButton;
                @DownMenuButton.performed += instance.OnDownMenuButton;
                @DownMenuButton.canceled += instance.OnDownMenuButton;
                @ToggleAutoActive.started += instance.OnToggleAutoActive;
                @ToggleAutoActive.performed += instance.OnToggleAutoActive;
                @ToggleAutoActive.canceled += instance.OnToggleAutoActive;
                @ConfirmMenuButton.started += instance.OnConfirmMenuButton;
                @ConfirmMenuButton.performed += instance.OnConfirmMenuButton;
                @ConfirmMenuButton.canceled += instance.OnConfirmMenuButton;
                @BackMenuButton.started += instance.OnBackMenuButton;
                @BackMenuButton.performed += instance.OnBackMenuButton;
                @BackMenuButton.canceled += instance.OnBackMenuButton;
                @WakeMinions.started += instance.OnWakeMinions;
                @WakeMinions.performed += instance.OnWakeMinions;
                @WakeMinions.canceled += instance.OnWakeMinions;
            }
        }
    }
    public IngameActions @Ingame => new IngameActions(this);
    private int m_GamepadSchemeSchemeIndex = -1;
    public InputControlScheme GamepadSchemeScheme
    {
        get
        {
            if (m_GamepadSchemeSchemeIndex == -1) m_GamepadSchemeSchemeIndex = asset.FindControlSchemeIndex("Gamepad Scheme");
            return asset.controlSchemes[m_GamepadSchemeSchemeIndex];
        }
    }
    public interface IIngameActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnBaseMinionControlGroup(InputAction.CallbackContext context);
        void OnRangedMinionControlGroup(InputAction.CallbackContext context);
        void OnTankMinionControlGroup(InputAction.CallbackContext context);
        void OnMagicMinionControlGroup(InputAction.CallbackContext context);
        void OnUpMenuButton(InputAction.CallbackContext context);
        void OnLeftMenuButton(InputAction.CallbackContext context);
        void OnRightMenuButton(InputAction.CallbackContext context);
        void OnDownMenuButton(InputAction.CallbackContext context);
        void OnToggleAutoActive(InputAction.CallbackContext context);
        void OnConfirmMenuButton(InputAction.CallbackContext context);
        void OnBackMenuButton(InputAction.CallbackContext context);
        void OnWakeMinions(InputAction.CallbackContext context);
    }
}
